create table employee (id bigint generated by default as identity, address varchar(255), name varchar(255), primary key (id));

insert into employee (name, address) values ('Radha Krishnan', 'Kathmandu'); 
insert into employee (name, address) values ('Pankaj', 'Pokhara'); 